---
sudo: required

services:
  - docker

env:
  - VERSION=0.10.12

install:
  - docker build -t "lgatica/django-caddy:$VERSION" -t lgatica/django-caddy:latest .

script:
  - docker run --rm "lgatica/django-caddy:$VERSION" --version

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push "lgatica/django-caddy:$VERSION" && docker push lgatica/django-caddy:latest
  skip_cleanup: true
  on:
    branch: master
