---
sudo: required

services:
  - docker

env:
  - VERSION=0.10.9

install:
  - docker build -t "lgatica/django-caddy:$VERSION" -t lgatica/django-caddy:latest .

script:
  - docker run --rm "lgatica/django-caddy:$VERSION" --version

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push "lgatica/django-caddy:$VERSION"
  - docker push lgatica/django-caddy:latest
