FROM alpine:3.6@sha256:d6bfc3baf615dc9618209a8d607ba2a8103d9c8a405b3bd8741d88b4bef36478

MAINTAINER Leonardo Gatica <lgatica@protonmail.com>

LABEL caddy_version="0.9.4" architecture="amd64"

ENV PORT 8000

RUN apk add --no-cache openssh-client git tar curl

RUN curl --silent --show-error --fail --location \
      --header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" -o - \
      "https://github.com/mholt/caddy/releases/download/v0.9.4/caddy_linux_amd64.tar.gz" \
    | tar --no-same-owner -C /usr/bin -xz \
 && mv /usr/bin/caddy_linux_amd64 /usr/bin/caddy \
 && chmod 0755 /usr/bin/caddy \
 && /usr/bin/caddy -version

EXPOSE 80 443 2015
VOLUME /root/.caddy
WORKDIR /srv

COPY Caddyfile /etc/Caddyfile

ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout"]
